### ISSUE TITLE
<ap Doesn't respect current date of my timezone

### ISSUE THREAD

**Issue by csbodine** [vlee489/Turnip-Bot#39]
I live in UTC-6:00. On several occasions I've tried to add prices in my evening and TurnipBot adds it to the PM of the following day. Attached is a screenshot from last night 2020-06-09 20:36Z-6:00. I added my PM prices and TurnipBot put it in the "10/06/2020 at PM" bucket which causes the followup TST command to fail.

<img width="512" alt="image" src="https://user-images.githubusercontent.com/6403612/84275564-7465fa00-aaee-11ea-92f5-d09ba295a4e9.png">

My suggestions are to either ask for a TZ value per user or to add an override to specify Day of the Week such as <ap Tues pm 171

**Comment by csbodine** [comment]
I found the setTimezone command which covers this issue. Sorry I wasn't paying more attention.

**Comment by vlee489** [comment]
`<help command` gives more details for each command, there was always a data override available

**Comment by vlee489** [comment]
For anyone looking at this issue in the future, your 2 options are as follows 

## Option one
Set a timezone

use `<help setTimezone` to get started with the command

## Option Two
Place a manual date override at the end of a turnip command in the format `DD/MM/YYYY`

Example `<ap pm 171 10/06/2020` This overrides the date to 10th June 2020


Turnip Bot has no way to tell where you are from the info given to us from Discord, you do have to add the info yourself. Be default dates are tied to UK time (BST/GMT)

Details for the commands are over at the [Wiki](https://github.com/vlee489/Turnip-Bot/wiki)
